import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/ui/navbar/Navbar";
import Sidebar from "./components/ui/sidebar/Sidebar";
import Clientprovider from "../app/queryClient/Clientprovider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex">
        <Clientprovider>
          <Sidebar />
          <div className="flex-1 flex-col flex">
            <Navbar />
            <main className="p-4">{children}</main>
          </div>
        </Clientprovider>
      </body>
    </html>
  );
}
